bin

diff --git a/bin/pio-class b/bin/pio-class
--- a/bin/pio-class
+++ b/bin/pio-class
@@ -46,22 +46,22 @@ fi
 
 # Make sure the Apache Spark version meets the prerequisite if it is a binary
 # distribution
-MIN_SPARK_VERSION="1.3.0"
-if [ -z "$SPARK_HOME" ]; then
-  echo -e "\033[0;31mSPARK_HOME must be set in conf/pio-env.sh, or in the environment!\033[0m"
-  exit 1
-elif [ -r "$SPARK_HOME/RELEASE" ]; then
-  SPARK_VERSION=`head -n 1 $SPARK_HOME/RELEASE | awk '{print $2}'`
-  if [ -z "$SPARK_VERSION" ]; then
-    echo -e "\033[0;35m$SPARK_HOME contains an empty RELEASE file. This is a known problem with certain vendors (e.g. Cloudera). Please make sure you are using at least $MIN_SPARK_VERSION.\033[0m"
-  elif semverLT ${SPARK_VERSION} ${MIN_SPARK_VERSION}; then
-    echo -e "\033[0;31mYou have Apache Spark $SPARK_VERSION at $SPARK_HOME which does not meet the minimum version requirement of $MIN_SPARK_VERSION.\033[0m"
-    echo -e "\033[0;31mAborting.\033[0m"
-    exit 1
-  fi
-else
-  echo -e "\033[0;35m$SPARK_HOME is probably an Apache Spark development tree. Please make sure you are using at least $MIN_SPARK_VERSION.\033[0m"
-fi
+#MIN_SPARK_VERSION="1.3.0"
+#if [ -z "$SPARK_HOME" ]; then
+#  echo -e "\033[0;31mSPARK_HOME must be set in conf/pio-env.sh, or in the environment!\033[0m"
+#  exit 1
+#elif [ -r "$SPARK_HOME/RELEASE" ]; then
+#  SPARK_VERSION=`head -n 1 $SPARK_HOME/RELEASE | awk '{print $2}'`
+#  if [ -z "$SPARK_VERSION" ]; then
+#    echo -e "\033[0;35m$SPARK_HOME contains an empty RELEASE file. This is a known problem with certain vendors (e.g. Cloudera). Please make sure you are using at least $MIN_SPARK_VERSION.\033[0m"
+#  elif semverLT ${SPARK_VERSION} ${MIN_SPARK_VERSION}; then
+#    echo -e "\033[0;31mYou have Apache Spark $SPARK_VERSION at $SPARK_HOME which does not meet the minimum version requirement of $MIN_SPARK_VERSION.\033[0m"
+#    echo -e "\033[0;31mAborting.\033[0m"
+#    exit 1
+#  fi
+#else
+#  echo -e "\033[0;35m$SPARK_HOME is probably an Apache Spark development tree. Please make sure you are using at least $MIN_SPARK_VERSION.\033[0m"
+#fi
 
 # Find the java binary
 if [ -n "${JAVA_HOME}" ]; then
@@ -83,6 +83,13 @@ if [[ "$?" != "0" ]]; then
 else
   CLASSPATH=${classpath_output}
 fi
+
+MAPR_HADOOP_CLASSPATH=`hadoop classpath`
+MAPR_SPARK_CLASSPATH="`mapr classpath`:$MAPR_HADOOP_CLASSPATH"
+source /opt/mapr/spark/spark-1.6.1/mapr-util/generate-classpath.sh
+generate_compatible_classpath "spark" "1.6.1" "hbase"
+MAPR_HBASE_CLASSPATH=${generated_classpath}
+CLASSPATH="$CLASSPATH:$MAPR_SPARK_CLASSPATH:$MAPR_HBASE_CLASSPATH"
 
 export CLASSPATH
 
